<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>defence-domain</artifactId>
        <groupId>uk.gov.moj.cpp.defence</groupId>
        <version>25.104.0-M1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>uk.gov.moj.cpp.defence</groupId>
    <artifactId>defence-domain-event</artifactId>

    <properties>
        <skip.schema.pojo.generation>false</skip.schema.pojo.generation>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.framework-api</groupId>
            <artifactId>framework-api-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.generators</groupId>
                <artifactId>pojo-generation-plugin</artifactId>
                <executions>
                    <execution>
                        <id>pojo-generation</id>
                        <configuration>
                            <basePackageName>uk.gov.moj.cpp.events.people</basePackageName>
                            <sourceDirectory>${project.basedir}/src/raml/json/schema
                            </sourceDirectory>
                            <generatorProperties implementation="uk.gov.justice.generation.pojo.core.PojoGeneratorProperties">
                                <plugins>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.typemodifying.ReferenceCustomReturnTypePlugin</plugin>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.typemodifying.FormatCustomReturnTypePlugin</plugin>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.classmodifying.AddEventAnnotationToClassPlugin</plugin>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.classmodifying.MakeClassSerializablePlugin</plugin>
                                </plugins>
                                <typeMappings>
                                    <typeMapping>
                                        <name>uuid</name>
                                        <type>reference</type>
                                        <implementation>java.util.UUID</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date</name>
                                        <type>reference</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date</name>
                                        <type>format</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date-time</name>
                                        <type>format</type>
                                        <implementation>java.time.ZonedDateTime</implementation>
                                    </typeMapping>
                                </typeMappings>
                            </generatorProperties>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>defence-datatypes-common</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.core.domain</groupId>
                        <artifactId>common-core-domain</artifactId>
                        <version>${coredomain.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
