<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>uk.gov.moj.cpp.common</groupId>
        <artifactId>service-parent-pom</artifactId>
        <version>17.104.0</version>
    </parent>

    <groupId>uk.gov.moj.cpp.defence</groupId>
    <artifactId>defence-parent</artifactId>
    <version>17.104.103-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <jgitflow.maven.developBranchName>main</jgitflow.maven.developBranchName>
        <domain.test.dsl.version>0.1.0</domain.test.dsl.version>
        <sonar.jacoco.itReportPath>${project.basedir}/../target/jacoco-it.exec
        </sonar.jacoco.itReportPath>
        <sonar.report.export.path>sonar-report.json</sonar.report.export.path>
        <sonar.scm.provider>git</sonar.scm.provider>
        <mvn.site.url>file://${project.build.directory}/site</mvn.site.url>

        <!-- move to common bom -->
        <commons.dbutils.version>1.7</commons.dbutils.version>
        <maven-cucumber-reporting-version>2.0.0</maven-cucumber-reporting-version>
        <sonar-maven-plugin.version>3.11.0.3922</sonar-maven-plugin.version>

        <!--Context Dependencies-->
        <people.version>2.0.114</people.version>
        <charging.version>2.0.274</charging.version>
        <usersgroups.version>17.104.48</usersgroups.version>
        <progression.version>17.0.286</progression.version>
        <referencedataoffences.version>17.104.52</referencedataoffences.version>
        <json-generator.version>0.1.0</json-generator.version>
        <criminal-court-public-model.version>${coredomain.version}</criminal-court-public-model.version>
        <coredomain.version>17.104.4</coredomain.version>
        <material.version>17.0.79</material.version>
        <referencedata.version>17.104.140</referencedata.version>
        <listing.version>17.104.8</listing.version>
        <hearing.version>17.104.186</hearing.version>
        <system.documentgenerator.client.version>1.0.4</system.documentgenerator.client.version>
        <systemdocgenerator.version>17.104.114</systemdocgenerator.version>
        <sonar.coverage.exclusions>
            **/uk/gov/justice/core/**/*,
            **/uk/gov/moj/cpp/defence/persistence/entity/**/*,
            **/uk/gov/moj/cpp/defence/common/util/**/*,
            **/uk/gov/moj/defence/domain/**/*,
            **/uk/gov/moj/defence/command/error/**/*,
            **/uk/gov/justice/cps/defence/**/*
        </sonar.coverage.exclusions>
    </properties>

    <modules>
        <module>defence-common</module>
        <module>defence-datatypes-common</module>
        <module>defence-test-utils</module>
        <module>defence-command</module>
        <module>defence-event</module>
        <module>defence-usergroup-service</module>
        <module>defence-external-query-service</module>
        <module>defence-query</module>
        <module>defence-viewstore</module>
        <module>defence-domain</module>
        <module>defence-integration-test</module>
        <module>defence-service</module>
        <module>defence-event-sources</module>
        <module>defence-healthchecks</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>external.atlassian.jgitflow</groupId>
                    <artifactId>jgitflow-maven-plugin</artifactId>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <archiveClasses>true</archiveClasses>
                    <attachClasses>true</attachClasses>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>${sonar-maven-plugin.version}</version>
            </plugin>
        </plugins>
    </build>

    <!-- Test dependencies -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>uk.gov.justice.services</groupId>
                <artifactId>test-utils-core</artifactId>
                <version>${cpp.framework.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice.utils</groupId>
                <artifactId>test-utils-logging-simple</artifactId>
                <version>${framework-libraries.version}</version>
                <scope>test</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>commons-dbutils</groupId>
                <artifactId>commons-dbutils</artifactId>
                <scope>test</scope>
                <version>${commons.dbutils.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <distributionManagement>
        <site>
            <id>site</id>
            <url>${mvn.site.url}</url>
        </site>
    </distributionManagement>
</project>
