<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>defence-parent</artifactId>
        <groupId>uk.gov.moj.cpp.defence</groupId>
        <version>25.104.0-M1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>defence-event</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>defence-event-processor</module>
        <module>defence-event-listener</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>messaging-adapter-generator-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.defence</groupId>
                        <artifactId>defence-event-sources</artifactId>
                        <classifier>yaml</classifier>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>messaging-client-generator-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.defence</groupId>
                        <artifactId>defence-event-sources</artifactId>
                        <classifier>yaml</classifier>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>


</project>
