<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>defence-viewstore</artifactId>
        <groupId>uk.gov.moj.cpp.defence</groupId>
        <version>25.104.0-M1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>defence-viewstore-liquibase</artifactId>

    <properties>
        <sonar.skip>true</sonar.skip>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>Create defence context schema</id>
                        <configuration>
                            <propertyFile>src/main/resources/liquibase.properties</propertyFile>
                            <contexts>${liquibase.context}</contexts>
                        </configuration>
                        <goals>
                            <goal>update</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.liquibase</groupId>
                        <artifactId>liquibase-core</artifactId>
                        <version>${liquibase.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
