<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>defence-domain</artifactId>
        <groupId>uk.gov.moj.cpp.defence</groupId>
        <version>25.104.0-M1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>uk.gov.moj.cpp.defence</groupId>
    <artifactId>defence-domain-aggregate</artifactId>

    <properties>
        <maven.cucumber.reporting.plugin.version>2.0.0</maven.cucumber.reporting.plugin.version>
        <skip.schema.pojo.generation>false</skip.schema.pojo.generation>
    </properties>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>defence-domain-event</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>defence-domain-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>defence-usergroup-service</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.framework-api</groupId>
            <artifactId>framework-api-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>domain-test-dsl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.utils</groupId>
            <artifactId>utilities-core</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.schema</groupId>
                <artifactId>catalog-generation-plugin</artifactId>
                <configuration>
                    <sourceDirectory>${project.basedir}/src/raml/json/schema</sourceDirectory>
                </configuration>
            </plugin>
        </plugins>
    </build>


    <profiles>
        <profile>
            <id>dsl-domain</id>
            <activation>
                <file>
                    <exists>src/test/resources/domain-features/</exists>
                </file>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <dependenciesToScan>
                                <dependency>uk.gov.justice.services:domain-test-dsl</dependency>
                            </dependenciesToScan>
                            <classesDirectory>target/classes/</classesDirectory>
                            <includes>*.class</includes>
                            <testClassesDirectory>target/test-classes/</testClassesDirectory>
                            <includes>*.class</includes>
                            <additionalClasspathElements>
                                <additionalClasspathElement>target/classes/
                                </additionalClasspathElement>
                            </additionalClasspathElements>

                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>net.masterthought</groupId>
                        <artifactId>maven-cucumber-reporting</artifactId>
                        <version>${maven-cucumber-reporting-version}</version>
                        <executions>
                            <execution>
                                <id>execution</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                                <configuration>
                                    <projectName>${project.artifactId}</projectName>
                                    <outputDirectory>
                                        ${project.build.directory}/site/cucumber-reports
                                    </outputDirectory>
                                    <cucumberOutput>${project.build.directory}/cucumber.json
                                    </cucumberOutput>
                                    <skippedFails>true</skippedFails>
                                    <buildNumber>${ci.build}</buildNumber>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
