<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>defence-command</artifactId>
        <groupId>uk.gov.moj.cpp.defence</groupId>
        <version>25.104.0-M1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>defence-command-handler</artifactId>
    <packaging>war</packaging>

    <properties>
        <cpp.service-component>COMMAND_HANDLER</cpp.service-component>
        <skip.schema.pojo.generation>false</skip.schema.pojo.generation>
     </properties>

    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>defence-usergroup-service</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.common</groupId>
            <artifactId>command-handler</artifactId>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.defence</groupId>
            <artifactId>defence-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>defence-domain-aggregate</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <artifactId>framework-api-core</artifactId>
            <groupId>uk.gov.justice.framework-api</groupId>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>core</artifactId>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.utils</groupId>
            <artifactId>test-utils-logging-simple</artifactId>
            <scope>test</scope>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>defence-domain-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>defence-datatypes-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>defence-test-utils</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.justice.services</groupId>
            <artifactId>test-utils-enveloper-provider</artifactId>
            <version>${cpp.framework.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.core.domain</groupId>
            <artifactId>criminal-court-public-model</artifactId>
            <version>${coredomain.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.core.domain</groupId>
            <artifactId>common-core-domain</artifactId>
            <version>${coredomain.version}</version>
        </dependency>
        <dependency>
            <groupId>uk.gov.moj.cpp.defence</groupId>
            <artifactId>defence-query-view</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>uk.gov.justice.generators</groupId>
                <artifactId>pojo-generation-plugin</artifactId>
                <executions>
                    <execution>
                        <id>pojo-generation</id>
                        <configuration>
                            <basePackageName>uk.gov.moj.cpp.events.defence</basePackageName>
                            <sourceDirectory>${project.basedir}/src/raml/json/schema</sourceDirectory>
                            <generatorProperties implementation="uk.gov.justice.generation.pojo.core.PojoGeneratorProperties">
                                <plugins>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.typemodifying.ReferenceCustomReturnTypePlugin</plugin>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.typemodifying.FormatCustomReturnTypePlugin</plugin>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.classmodifying.AddAdditionalPropertiesToClassPlugin</plugin>
                                    <plugin>uk.gov.justice.generation.pojo.plugin.classmodifying.MakeClassSerializablePlugin</plugin>
                                </plugins>
                                <typeMappings>
                                    <typeMapping>
                                        <name>uuid</name>
                                        <type>reference</type>
                                        <implementation>java.util.UUID</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date</name>
                                        <type>reference</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date</name>
                                        <type>format</type>
                                        <implementation>java.time.LocalDate</implementation>
                                    </typeMapping>
                                    <typeMapping>
                                        <name>date-time</name>
                                        <type>format</type>
                                        <implementation>java.time.ZonedDateTime</implementation>
                                    </typeMapping>
                                </typeMappings>
                            </generatorProperties>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>defence-datatypes-common</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.core.domain</groupId>
                        <artifactId>common-core-domain</artifactId>
                        <version>${coredomain.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>uk.gov.justice.framework-generators</groupId>
                <artifactId>rest-client-generator-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.referencedata.offences</groupId>
                        <version>${referencedataoffences.version}</version>
                        <artifactId>referencedataoffences-query-api</artifactId>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>uk.gov.moj.cpp.usersgroups</groupId>
                        <artifactId>usersgroups-query-api</artifactId>
                        <version>${usersgroups.version}</version>
                        <classifier>raml</classifier>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>jakarta.platform</groupId>
                        <artifactId>jakarta.jakartaee-api</artifactId>
                        <version>${javaee-api.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>jakarta.xml.bind</groupId>
                        <artifactId>jakarta.xml.bind-api</artifactId>
                        <version>${jakarta.xml.bind-api.raml.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
         </plugins>
    </build>
</project>
